CREATE TABLE `teachers` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `madrasa_id` INTEGER NOT NULL,
    `name` VARCHAR(180) NOT NULL,
    `qualification` TEXT NOT NULL,
    `specialization` VARCHAR(240) NOT NULL,
    `experience_years` INTEGER NOT NULL DEFAULT 0,
    `students_count` INTEGER NOT NULL DEFAULT 0,
    `assigned_students_count` INTEGER NULL,
    `phone` VARCHAR(30) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `status` VARCHAR(30) NOT NULL DEFAULT 'Active',
    `avatar` VARCHAR(1000) NULL,
    `sanad` TEXT NULL,
    `salary_etb` DOUBLE NULL,
    `is_certified` BOOLEAN NOT NULL DEFAULT false,
    `is_featured` BOOLEAN NOT NULL DEFAULT false,
    `is_published` BOOLEAN NOT NULL DEFAULT false,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,
    INDEX `teachers_madrasa_id_idx`(`madrasa_id`),
    INDEX `teachers_is_published_is_featured_idx`(`is_published`, `is_featured`),
    PRIMARY KEY (`id`),
    CONSTRAINT `teachers_madrasa_id_fkey` FOREIGN KEY (`madrasa_id`) REFERENCES `madrasas`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
