CREATE TABLE `students` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(180) NOT NULL,
    `arabic_name` VARCHAR(180) NULL,
    `gender` VARCHAR(20) NOT NULL,
    `age` INTEGER NOT NULL,
    `madrasa_id` INTEGER NOT NULL,
    `class_name` VARCHAR(180) NOT NULL,
    `teacher_id` VARCHAR(80) NULL,
    `teacher_name` VARCHAR(180) NULL,
    `enrollment_date` VARCHAR(10) NOT NULL,
    `attendance_rate` DOUBLE NOT NULL DEFAULT 100,
    `quran_juz_completed` INTEGER NOT NULL DEFAULT 0,
    `current_juz` INTEGER NOT NULL DEFAULT 1,
    `current_juz_progress` DOUBLE NOT NULL DEFAULT 0,
    `hifz_status` JSON NOT NULL,
    `tajweed_rating` VARCHAR(40) NOT NULL,
    `exam_score_avg` DOUBLE NOT NULL DEFAULT 0,
    `parent_name` VARCHAR(180) NOT NULL,
    `parent_phone` VARCHAR(40) NOT NULL,
    `guardian_name` VARCHAR(180) NULL,
    `guardian_phone` VARCHAR(40) NULL,
    `sabaq_surah` VARCHAR(180) NULL,
    `sabaq_ayah_start` INTEGER NULL,
    `sabaq_ayah_end` INTEGER NULL,
    `sabaqi_juz` INTEGER NULL,
    `manzil_juz` VARCHAR(180) NULL,
    `daily_attendance` VARCHAR(30) NULL,
    `level` VARCHAR(180) NULL,
    `status` VARCHAR(30) NOT NULL DEFAULT 'Active',
    `avatar` VARCHAR(1000) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,
    INDEX `students_madrasa_id_idx`(`madrasa_id`),
    INDEX `students_name_idx`(`name`),
    PRIMARY KEY (`id`),
    CONSTRAINT `students_madrasa_id_fkey` FOREIGN KEY (`madrasa_id`) REFERENCES `madrasas`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
