CREATE TABLE `zakat_distributions` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `asnaf_category` VARCHAR(120) NOT NULL,
  `arabic_name` VARCHAR(180) NULL,
  `woreda_district` VARCHAR(180) NULL,
  `beneficiary_count` INTEGER NOT NULL DEFAULT 1,
  `total_disbursed_etb` DECIMAL(14, 2) NOT NULL,
  `last_disbursal_date` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `distribution_channel` VARCHAR(120) NULL,
  `lead_officer` VARCHAR(150) NULL,
  `notes` TEXT NOT NULL,
  `beneficiary_name` VARCHAR(150) NULL,
  `category` VARCHAR(100) NULL,
  `amount_etb` DECIMAL(14, 2) NULL,
  `district` VARCHAR(180) NULL,
  `verification_status` VARCHAR(40) NULL,
  `disbursement_date` DATETIME(3) NULL,
  `approved_by` VARCHAR(150) NULL,
  `created_by_id` INTEGER NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX `zakat_distributions_asnaf_category_last_disbursal_date_idx` (`asnaf_category`, `last_disbursal_date`),
  INDEX `zakat_distributions_district_last_disbursal_date_idx` (`district`, `last_disbursal_date`),
  INDEX `zakat_distributions_created_by_id_created_at_idx` (`created_by_id`, `created_at`),
  PRIMARY KEY (`id`),
  CONSTRAINT `zakat_distributions_created_by_id_fkey` FOREIGN KEY (`created_by_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
