CREATE TABLE `ulema_profiles` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(180) NOT NULL,
    `arabic_name` VARCHAR(180) NULL,
    `title` VARCHAR(180) NOT NULL,
    `specializations` JSON NOT NULL,
    `district` VARCHAR(120) NOT NULL,
    `assigned_mosque_id` VARCHAR(120) NULL,
    `assigned_mosque_name` VARCHAR(180) NULL,
    `qualifications` JSON NOT NULL,
    `languages` JSON NOT NULL,
    `areas_of_service` JSON NOT NULL,
    `biography` TEXT NOT NULL,
    `contact_phone` VARCHAR(30) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `status` VARCHAR(30) NOT NULL DEFAULT 'Active',
    `avatar` VARCHAR(1000) NULL,
    `years_of_dawah` INTEGER NOT NULL DEFAULT 0,
    `is_featured` BOOLEAN NOT NULL DEFAULT false,
    `is_published` BOOLEAN NOT NULL DEFAULT false,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,
    INDEX `ulema_profiles_is_published_is_featured_idx`(`is_published`, `is_featured`),
    INDEX `ulema_profiles_district_idx`(`district`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
